# Generated by Django 5.2.7 on 2026-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0007_seed_practice_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
