# Generated by Django 5.2.7 on 2026-04-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_add_stripe_invoice_number'),
        ('finances', '0006_invoice_voided_status'),
    ]

    operations = [
    ]
