name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Deploy on droplet
        run: /home/deploy/apps/Lydias-Law-Site/deploy.sh